extraArgs:
  provider: oidc
  email-domain: "*"
  oidc-issuer-url: https://login.openraven.net/oauth2/aus1i055qhbS5kjvB0h8
  cookie-name: _oauth2_proxy
  request-logging: "true"
  pass-access-token: "true"
  pass-basic-auth: "true"
  pass-user-headers: "true"
  pass-host-header: "true"
  pass-authorization-header: "false"
  set-xauthrequest: "true"
  set-authorization-header: "true"
  cookie-secure: "true"
  cookie-refresh: "1h"
  skip-provider-button: "true"
  skip-auth-regex: "/robots.txt|/favicon.ico"
  skip-jwt-bearer-tokens: "true"
  silence-ping-logging: "true"
  ssl-upstream-insecure-skip-verify: "true"
  ssl-insecure-skip-verify: "true"
  session-store-type: "redis"
  redis-connection-url: "redis://redis-master.ui.svc.cluster.local:6379/0"

image:
  tag: "v5.0.0"
  pullPolicy: "IfNotPresent"

service:
  type: ClusterIP
  port: 4180
  annotations: {}

ingress:
  enabled: true
  path: "/oauth2"

livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
