{{ $gitUrl := env "HELMFILE_GIT_URL" | default "git::https://gitlab.com/openraven/open/helm-charts/helmfiles.git" }}
{{ $gitRef := env "HELMFILE_GIT_REF" | default "__GITLAB_CI_FIX_THIS__" }}
{{ $baseDir := printf "%s@helmfile.d" $gitUrl }}
helmfiles:
- path: {{ $baseDir }}/etcd-prune.yaml?ref={{ $gitRef }}
{{ if eq (env "CLUSTER_TYPE") "saas" }}
# THIS MUST BE VERY EARLY
- path: {{ $baseDir }}/kiam.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/logdna-agent.yaml?ref={{ $gitRef }}
{{ end }}
- path: {{ $baseDir }}/openraven-datadog.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/openraven-admin.yaml?ref={{ $gitRef }}
{{/* use the previous one for old clusters */}}
{{ $volProv := "kubernetes.io/aws-ebs" }}
{{ if (env "CLUSTER_TAGS_JSON") }}
- path: {{ $baseDir }}/aws-ebs-csi-driver.yaml?ref={{ $gitRef }}
{{ $volProv = "ebs.csi.aws.com" }}
{{ end }}
- path: {{ $baseDir }}/default-storage-class.yaml?ref={{ $gitRef }}
  values:
  - provisioner: {{ $volProv }}
- path: {{ $baseDir }}/ingress.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/redis.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/oauth2-proxy.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/kubernetes-dashboard.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/kafka.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/elasticsearch.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/productui.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/introspection.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/elastic-search-node-client.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/cross-account.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/account-management.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/asset-groups.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/cluster-upgrade.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/odin-metrics.yaml?ref={{ $gitRef }}

{{/*
We are purposefully picking an environment variable that cluster-upgrade
will have but that helmfile0 does not, so this gets installed post, err, install;
you can pick almost any one from the list in charts/cluster-upgrade/templates/deployment.yaml
so long as it's not in the list in helmfile0.pod.yml */}}
{{ if env "OPENRAVEN_UPGRADES_NAME" }}
- path: {{ $baseDir }}/graphql-api-server.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/metrics-server.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/dmap.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/s3-scan-service.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/dmap-scheduler.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/cloudwatcher.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/aws-discovery-svc.yaml?ref={{ $gitRef }}
- path: {{ $baseDir }}/policy.yaml?ref={{ $gitRef }}
{{ if env "OPENRAVEN_UNRELEASED_FEATURES" }}
{{ end }}
{{ if env "OPENRAVEN_UNSTABLE_UNRELEASED_FEATURES" }}
{{ end }}
{{ end }}
