helmfiles:
{{ $gitUrl := env "HELMFILE_GIT_URL" | default "git::https://git.openraven.io/open/helm-charts/helmfiles.git" }}
{{ $gitRef := env "HELMFILE_GIT_REF" | default "__GITLAB_CI_FIX_THIS__" }}
- path: {{ $gitUrl }}@helmfile.d/storage-class.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/ingress.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/oauth2-proxy.yaml?ref={{ $gitRef }}
{{ if (env "CERT_MANAGER_ZONE_ID") }}
- path: {{ $gitUrl }}@helmfile.d/cert-manager.yaml?ref={{ $gitRef }}
{{ end }}
- path: {{ $gitUrl }}@helmfile.d/kafka.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/orientdb.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/productui.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/graph-explorer.yaml?ref={{ $gitRef }}
{{/*
We are purposefully picking an environment variable that cluster-upgrade
will have but that helmfile0 does not, so this gets installed post, err, install;
you can pick almost any one from the list in charts/cluster-upgrade/templates/deployment.yaml
so long as it's not in the list in helmfile0.pod.yml */}}
{{ if env "OPENRAVEN_UPGRADES_NAME" }}
- path: {{ $gitUrl }}@helmfile.d/aws-discovery-svc.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/arcade-analytics.yaml?ref={{ $gitRef }}
{{ end }}
- path: {{ $gitUrl }}@helmfile.d/cross-account.yaml?ref={{ $gitRef }}
- path: {{ $gitUrl }}@helmfile.d/account-management.yaml?ref={{ $gitRef }}
{{ if (env "INCLUDE_DMAP") }}
- path: {{ $gitUrl }}@helmfile.d/dmap.yaml?ref={{ $gitRef }}
{{ end }}
{{ if (env "INCLUDE_PORTSCAN") }}
- path: {{ $gitUrl }}@helmfile.d/portscan.yaml?ref={{ $gitRef }}
{{ end }}
- path: {{ $gitUrl }}@helmfile.d/cluster-upgrade.yaml?ref={{ $gitRef }}
