repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
{{ $clientId     := requiredEnv "SERVICE_CLIENT_ID" }}
{{ $clientSecret := requiredEnv "SERVICE_CLIENT_SECRET" }}
{{ $cookieSecret := requiredEnv "COOKIE_SECRET" }}
{{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
{{ define "cert-issuer-name" }}
{{- if not (env "CERT_MANAGER_EMAIL") -}}
self-signed
{{- else -}}
letsencrypt-prod
{{- end -}}
{{ end }}
- name: oauth2-proxy
  namespace: kube-system
  chart: stable/oauth2-proxy
  # https://github.com/helm/charts/blob/master/stable/oauth2-proxy/Chart.yaml#L2
  version: 2.1.1
  values:
  - ./values/oauth2-proxy/2.1.1.yaml
  - global:
      serviceClientId: {{ $clientId }}
      serviceClientSecret: {{ $clientSecret }}
      openravenIngressHostname: {{ $ingHostname }}
  - config:
      clientID: {{ $clientId }}
      clientSecret: {{ $clientSecret }}
      cookieSecret: {{ $cookieSecret }}
  - extraArgs:
      upstream: https://{{ $ingHostname }}
      redirect-url: https://{{ $ingHostname }}/oauth2/callback
  - ingress:
      hosts:
        - {{ $ingHostname }}
      annotations:
        cert-manager.io/cluster-issuer: {{ template "cert-issuer-name" .}}
      tls:
        - secretName: oauth2-proxy-tls
          hosts:
            - {{ $ingHostname }}
