{{- $version := "v0.12.0" -}}
repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  # https://hub.helm.sh/charts/jetstack/cert-manager/v0.12.0
  version: {{ $version }}
  wait: true
  values:
  - ./values/cert-manager/{{ $version }}.yaml

  hooks:
  - events: ['presync']
    showlogs: true
    command: kubectl
    args:
    ## IMPORTANT: you MUST install the cert-manager CRDs **before** installing the
    ## cert-manager Helm chart
    - --v=5
    - apply
    - --validate=false
    - -f
    # no, don't do this, it has *everything* in it, which defeats the purpose of using helm
    # - https://github.com/jetstack/cert-manager/releases/download/{{ $version }}/cert-manager.yaml
    - https://github.com/jetstack/cert-manager/raw/{{ $version }}/deploy/manifests/00-crds.yaml
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
      kubectl label --overwrite namespace $my_ns "cert-manager.io/disable-validation=true"

- name: self-signed-issuer
  namespace: cert-manager
  chart: incubator/raw
  # https://hub.helm.sh/charts/incubator/raw/0.2.3
  version: 0.2.3
  wait: true
  force: true
  recreatePods: false
  values:
  - resources:
    - apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
        name: self-signed
      spec:
        selfSigned: {}
# now one can use the cert-manager annotation on the Ingress resources:
# annotations:
#    cert-manager.io/cluster-issuer: self-signed
# with "self-signed" matching the CI's "metadata.name"
# see: https://cert-manager.io/docs/usage/ingress/#supported-annotations

{{ if env "CERT_MANAGER_EMAIL" }}
- name: letsencrypt-prod-issuer
  namespace: cert-manager
  chart: incubator/raw
  version: 0.2.3
  wait: true
  force: true
  recreatePods: false
  values:
  - resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        namespace: cert-manager
        name: orvn-r53-aws-secret
      stringData:
        aws-secret-access-key: {{ requiredEnv "CERT_MANAGER_AWS_SECRET" | toJson }}

    - apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          email: {{ requiredEnv "CERT_MANAGER_EMAIL" | toJson }}
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-prod-key
          solvers:
          - dns01:
              route53:
                region: {{ requiredEnv "CERT_MANAGER_AWS_REGION" | toJson }}
                hostedZoneID: {{ requiredEnv "CERT_MANAGER_ZONE_ID" | toJson }}
                accessKeyID: {{ requiredEnv "CERT_MANAGER_AWS_KEY" | toJson }}
                secretAccessKeySecretRef:
                  name: orvn-r53-aws-secret
                  key: aws-secret-access-key
            selector:
              # https://cert-manager.io/docs/configuration/acme/#dns-zones
              dnsZones:
              - {{ requiredEnv "CERT_MANAGER_DOMAIN" | toJson }}
{{ end }}
