{{- $version := "7.0.5" }}
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: kafka
  namespace: kafka
  chart: bitnami/kafka
  # https://hub.helm.sh/charts/bitnami/kafka/7.0.5
  version: {{ $version }}
  # this apparently needs some TLC
  # needs:
  # - kube-system/default-storage-class
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
           kubectl create      namespace $my_ns
      fi
  - events: ['postsync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      # this is a concession for non CFN deployment setups
      if ! type ansible-playbook >/dev/null 2>&1; then
        exit 0
      fi
      # that KUBECONFIG comes from helmfile0's environment
      # these env names are consumed by the '-c kubectl' below
      export K8S_AUTH_KUBECONFIG="${KUBECONFIG}"
      export K8S_AUTH_NAMESPACE='{{`{{ .Release.Namespace }}`}}'
      export K8S_AUTH_POD=''
      k() {
        kubectl -n "$K8S_AUTH_NAMESPACE" "$@"
      }
      k_first_pod() {
        k get -o name pod -l app.kubernetes.io/component=zookeeper | head -1
      }
      k_pod_phase() {
        k get -o jsonpath='{.status.phase}' "$1"
      }
      for i in $(seq 1 30); do
        K8S_AUTH_POD="$(k_first_pod || true)"
        if [[ -n "$K8S_AUTH_POD" ]]; then
          break
        fi
        sleep 1
      done
      if [[ -z "${K8S_AUTH_POD}" ]]; then
        echo 'Unable to sniff out any zookeeper Pod' >&2
        exit 1
      fi
      for i in $(seq 1 30); do
        if [[ Running == "$(k_pod_phase "${K8S_AUTH_POD}")" ]]; then
          break
        fi
        sleep 1
      done
      playbook_fn=kafka-zookeeper-defaults.yml
      if [[ ! -e "$playbook_fn" ]]; then
        cat     >"$playbook_fn"<<YML
      - hosts: all
        gather_facts: no
        roles:
        - zookeeper-defaults
      YML
      fi
      exec ansible-playbook -vv -c kubectl -i ${K8S_AUTH_POD}, "$playbook_fn"
