{{- $version := "7.0.5" }}
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
- name: kafka-ns
  namespace: kube-system
  chart: incubator/raw
  # https://hub.helm.sh/charts/incubator/raw/0.2.3
  version: 0.2.3
  wait: true
  force: true
  recreatePods: false
  values:
  - resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: kafka

- name: kafka
  namespace: kafka
  chart: bitnami/kafka
  # https://hub.helm.sh/charts/bitnami/kafka/7.0.5
  version: {{ $version }}
  # this apparently needs some TLC
  # needs:
  # - kube-system/default-storage-class
