{{- $version := "0.1.2" }}
repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
- name: odb-namespace
  namespace: kube-system
  chart: incubator/raw
  # https://hub.helm.sh/charts/incubator/raw/0.2.3
  version: 0.2.3
  wait: true
  force: true
  recreatePods: false
  values:
  - resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: odb

- name: odb
  namespace: odb
  chart: incubator/orientdb
  # https://hub.helm.sh/charts/incubator/orientdb/0.1.2
  version: {{ $version }}
  values:
  - ./values/orientdb/{{ $version }}.yaml
