{{ $s3Bucket := env "HELM_S3_BUCKET" | default "openraven-deploy" }}
repositories:
- name: openraven
  url: https://{{ $s3Bucket }}.s3-us-west-2.amazonaws.com/charts

releases:
- name: cluster-upgrade
  namespace: cluster-upgrade
  chart: openraven/cluster-upgrade
  version: 0.0.5
  wait: true
  values:
  - global:
      frontEndClientId: {{ env "FRONTEND_CLIENT_ID" }}
      groupId: {{ env "GROUP_ID" }}
      helmBucket: {{ $s3Bucket }}
      serviceClientId: {{ env "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ env "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ env "OPENRAVEN_INGRESS_HOSTNAME" }}
