{{ $s3Bucket := env "HELM_S3_BUCKET" | default "openraven-deploy" }}
repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: openraven
  url: https://{{ $s3Bucket }}.s3-us-west-2.amazonaws.com/charts

releases:
- name: aws                            # name of this release
  namespace: aws                       # target namespace
  chart: openraven/openraven-deploy    # the chart being installed to create this release, referenced by `repository/chart` syntax
  version: 0.0.2                    # the semver of the chart. range constraint is supported
  missingFileHandler: Warn # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  # wait for k8s resources via --wait. Defaults to `false`
  wait: true
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 300
  # performs pods restart for the resource if applicable
  recreatePods: true
  # forces resource update through delete/recreate if needed
  force: true
  # set `false` to uninstall on sync
  installed: true
  # restores previous state in case of failed release
  atomic: true
  hooks:
  - events: ["presync"]
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
      if kubectl -n $my_ns get secret -o name odb-orientdb-secret; then exit 0; fi
      kubectl -n odb get secret odb-orientdb-secret -oyaml | sed s/"namespace: odb"/"namespace: $my_ns"/ | kubectl apply -f -
  values:
  - global:
      frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
      groupId: {{ requiredEnv "GROUP_ID" }}
      serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
