{{ $s3Bucket := env "HELM_S3_BUCKET" | default "openraven-deploy" }}
repositories:
- name: openraven
  url: https://{{ $s3Bucket }}.s3-us-west-2.amazonaws.com/charts

releases:
- name: ui
  namespace: ui
  chart: openraven/productui
  version: 0.0.1
  missingFileHandler: Warn
  wait: true
  timeout: 300
  recreatePods: true
  force: true
  installed: true
  atomic: true
  values:
  - global:
      frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
      groupId: {{ requiredEnv "GROUP_ID" }}
      serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
