repositories:
  {{ $s3Bucket := env "HELM_S3_BUCKET" | default "openraven-deploy" }}
  {{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
  {{ $ingHostname := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
  - name: openraven
    url: https://{{ $s3Bucket }}.{{ $s3BucketHost }}/charts

releases:
- name: explorer
  namespace: ui
  chart: openraven/graph-explorer
  version: 0.2003.0
  missingFileHandler: Warn
  wait: true
  timeout: 300
  recreatePods: true
  force: true
  installed: true
  atomic: true
  hooks:
  - events: ["presync"]
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
      if kubectl -n $my_ns get secret -o name odb-orientdb-secret; then exit 0; fi
      kubectl -n odb get secret odb-orientdb-secret -oyaml | sed s/"namespace: odb"/"namespace: $my_ns"/ | kubectl apply -f -
  values:
  - global:
      frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
      groupId: {{ requiredEnv "GROUP_ID" }}
      serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ $ingHostname }}
  - ingress:
      {{ if not (env "CERT_MANAGER_EMAIL") }}
      # thank goodness, it appears to *merge* this with the one in the chart's values.yaml
      annotations:
        cert-manager.io/cluster-issuer: self-signed
      {{ end }}
      tls:
      # be careful, this needs to be the same name from productui.yaml
      - secretName: productui-tls
        hosts:
        - {{ $ingHostname }}
