{{ $s3Bucket := env "HELM_S3_BUCKET" | default "openraven-deploy" }}
repositories:
- name: openraven
  url: https://{{ $s3Bucket }}.s3-us-west-2.amazonaws.com/charts

releases:
- name: cluster-upgrade
  namespace: cluster-upgrade
  chart: openraven/cluster-upgrade
  # the date suffix is for the updated helmfile in the container
  version: 0.0.6-20191227
  wait: true
  values:
  - global:
      frontEndClientId: {{ env "FRONTEND_CLIENT_ID" }}
      groupId: {{ env "GROUP_ID" }}
      helmBucket: {{ $s3Bucket }}
      serviceClientId: {{ env "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ env "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ env "OPENRAVEN_INGRESS_HOSTNAME" }}
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
