repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $includeRds   := false }}
  - name: openraven
    url: {{ $ourUrl }}

templates:
  default: &default
    namespace: "aws"
    chart: "openraven/aws-discovery-svc"
    version: 0.2753.0
    missingFileHandler: Warn
    wait: true
    timeout: 300
    recreatePods: true
    force: true
    installed: true
    atomic: true
    values:
    - global: &global
        frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
        groupId: {{ requiredEnv "GROUP_ID" }}
        serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
        serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
        openravenIngressHostname: {{ requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}

releases:
  - name: aws-consumer-svc
    <<: *default
    hooks:
    - events: ["presync"]
      showlogs: true
      command: bash
      args:
      - -exc
      - |
        my_ns="{{`{{ .Release.Namespace }}`}}"
        if ! kubectl get -o name namespace $my_ns; then
          kubectl create namespace $my_ns
        fi
    values:
    - ./values/odbRootPassword.yaml
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, consumer, prod
  - name: aws-s3-discovery-svc
    <<: *default
    values:
    - ./values/odbRootPassword.yaml
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, S3

  - name: aws-ec2-discovery-svc
    <<: *default
    values:
    - ./values/odbRootPassword.yaml
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, EC2

{{ if $includeRds }}
  - name: aws-rds-discovery-svc
    <<: *default
    values:
    - ./values/odbRootPassword.yaml
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, RDS
{{ end }}
