repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
- name: openraven
  url: {{ $ourUrl }}


{{/* these "env" values come from the helmfile0.pod.yml */}}
{{ define "cert-issuer-name" }}
{{- if not (env "CERT_MANAGER_EMAIL") -}}
self-signed
{{- else -}}
letsencrypt-prod
{{- end -}}
{{ end }}

releases:
- name: cross-account
  namespace: ui
  chart: openraven/cross-account
  version: 0.2746.0
  wait: false
  values:
  - global:
      groupId: {{ env "GROUP_ID" }}
      openravenIngressHostname: {{ $ingHostname }}

  - ingress:
      annotations:
        cert-manager.io/cluster-issuer: {{ template "cert-issuer-name" .}}
      tls:
      - secretName: www-tls
        hosts:
        - {{ $ingHostname }}

  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
