repositories:
  {{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
  {{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
  {{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
  {{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
  - name: openraven
    url: {{ $ourUrl }}

releases:
- name: arcade-analytics
  namespace: ui
  chart: openraven/arcade-analytics
  version: 0.130873962.1
  wait: true
  timeout: 300
  hooks:
  - events: ["presync"]
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
           kubectl create      namespace $my_ns
      fi
  values:
  - ./values/odbRootPassword.yaml
  - global:
      openravenIngressHostname: {{ $ingHostname }}
  - ingress:
      tls:
      # be careful, this needs to be the same name from productui.yaml
      - secretName: www-tls
        hosts:
        - {{ $ingHostname }}
