repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $clusterType  := env "CLUSTER_TYPE"        | default "dev" }}
{{ $profileBase := "default, producer, prod" }}
{{ if eq $clusterType "saas" }}
  {{ $profileBase = (print $profileBase ", saas") }}
{{ end }}
  - name: openraven-repo
    url: {{ $ourUrl }}

templates:
  default: &default
    namespace: "aws"
    chart: "openraven-repo/aws-discovery-svc"
    version: 0.213188773.0
    missingFileHandler: Warn
    timeout: 600
    installed: true
    values:
    - global: &global
        frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
        groupId: {{ requiredEnv "GROUP_ID" }}
        serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
        serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
        openravenIngressHostname: {{ requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}

releases:
  - name: aws-consumer-svc
    <<: *default
    hooks:
    - events: ["presync"]
      showlogs: true
      command: bash
      args:
      - -exc
      - |
        my_ns="{{`{{ .Release.Namespace }}`}}"
        if ! kubectl get -o name namespace $my_ns; then
          kubectl create namespace $my_ns
        fi
        kubectl annotate --overwrite ns $my_ns "iam.amazonaws.com/permitted=orvn-{{ env "GROUP_ID" }}-.*"

    values:
    - global: *global
    - resources:
        requests:
          memory: 2Gi
        limits:
          memory: 2Gi
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, consumer, prod

  - name: aws-account-iam-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, Accounts

  - name: aws-s3-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, S3

  - name: aws-s3objects-discovery-svc
    <<: *default
    values:
      - global: *global
      - extraEnv:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ $profileBase }}, S3Objects

  - name: aws-ec2-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, EC2

  - name: aws-rds-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, RDS

  - name: aws-efs-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, EFS

  - name: aws-dynamodb-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, dynamoDb

  - name: aws-redshift-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, RSH

  - name: aws-fsx-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, FSX

  - name: aws-backup-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, BACKUP

  - name: aws-ess-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, ESS

  - name: aws-elb-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, ELB

  - name: aws-elbv2-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, ELBV2
