repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
  - name: openraven-repo
    url: {{ $ourUrl }}

templates:
  default: &default
    namespace: "aws"
    chart: "openraven-repo/aws-discovery-svc"
    version: 0.198364854.0
    missingFileHandler: Warn
    timeout: 600
    installed: true
    values:
    - global: &global
        frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
        groupId: {{ requiredEnv "GROUP_ID" }}
        serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
        serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
        openravenIngressHostname: {{ requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}

releases:
  - name: aws-consumer-svc
    <<: *default
    hooks:
    - events: ["presync"]
      showlogs: true
      command: bash
      args:
      - -exc
      - |
        my_ns="{{`{{ .Release.Namespace }}`}}"
        if ! kubectl get -o name namespace $my_ns; then
          kubectl create namespace $my_ns
        fi
    values:
    - global: *global
    - resources:
        requests:
          memory: 2Gi
        limits:
          memory: 2Gi
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, consumer, prod

  - name: aws-account-iam-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, Accounts

  - name: aws-s3-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, S3

  - name: aws-ec2-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, EC2

  - name: aws-rds-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, RDS

  - name: aws-efs-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, EFS

  - name: aws-dynamodb-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, dynamoDb

  - name: aws-redshift-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, RSH

  - name: aws-fsx-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, FSX

  - name: aws-backup-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, BACKUP

  - name: aws-ess-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, ESS

  - name: aws-elb-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, ELB

  - name: aws-elbv2-discovery-svc
    <<: *default
    values:
    - global: *global
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, producer, prod, ELBV2
