repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $clusterType  := env "CLUSTER_TYPE"        | default "dev" }}
{{ $profileBase := "default, producer, prod" }}
{{ $groupId      := requiredEnv "GROUP_ID" }}
{{ if eq $clusterType "saas" }}
  {{ $profileBase = (print $profileBase ", saas") }}
{{ end }}
{{ $producers := (readFile "./values/aws-discovery-producers.yaml" | fromYaml) }}
  - name: openraven-repo
    url: {{ $ourUrl }}

templates:
  default: &default
    namespace: "aws"
    chart: "openraven-repo/aws-discovery-svc"
    version: 0.216446588.0
    missingFileHandler: Warn
    timeout: 600
    installed: true
    values:
    - global: &global
        frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
        groupId: {{ $groupId }}
        serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
        serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
        openravenIngressHostname: {{ requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}

releases:
  - name: aws-discovery-priority-class
    <<: *default
    values:
      - priorityClass:
          create: true

  - name: aws-consumer-svc
    <<: *default
    hooks:
    - events: ["presync"]
      showlogs: true
      command: bash
      args:
      - -exc
      - |
        my_ns="{{`{{ .Release.Namespace }}`}}"
        if ! kubectl get -o name namespace $my_ns; then
          kubectl create namespace $my_ns
        fi
        kubectl annotate --overwrite ns $my_ns "iam.amazonaws.com/permitted=orvn-{{ $groupId }}-.*"

    values:
    - global: *global
    - deployment:
        enabled: true
    - resources:
        requests:
          memory: 2Gi
        limits:
          memory: 2Gi
    - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: default, consumer, prod

{{- range $producers.producers }}
  - name: aws-{{ .name | lower }}-discovery-svc
    <<: *default
    values:
      - global: *global
      - cronJob:
          enabled: true
{{- if index . "schedule" }}
          schedule: {{ .schedule }}
{{- end }}
      - extraEnv:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ $profileBase }}, cronJob, {{ .name }}
{{- end }}

  # Handle s3Objects as a one off and run it as a deployment
  # it uses an in memory bloom filter that resets on every restart... we want to preserve that filter across runs.
  - name: aws-s3objects-discovery-svc
    <<: *default
    values:
      - global: *global
      - deployment:
          enabled: true
      - extraEnv:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $profileBase }}, S3Objects

  - name: aws-account-iam-discovery-svc
    <<: *default
    installed: false
  - name: aws-redshift-discovery-svc
    <<: *default
    installed: false
