repositories:
{{/* these "env" values come from the helmfile0.pod.yml */}}
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $s3Key        := env "HELM_S3_KEY"         | default "charts/helmfile.yaml" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
- name: openraven-repo
  url: {{ $ourUrl }}

releases:
- name: cluster-upgrade
  namespace: cluster-upgrade
  chart: openraven-repo/cluster-upgrade
  version: 0.194343397.2
  wait: false
  values:
  - ./values/clusterType.yaml.gotmpl
  - global:
      cookieSecret: {{ env "COOKIE_SECRET" | toJson }}
      frontEndClientId: {{ env "FRONTEND_CLIENT_ID" }}
      groupId: {{ env "GROUP_ID" }}
      serviceClientId: {{ env "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ env "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ env "OPENRAVEN_INGRESS_HOSTNAME" }}
      adminClientId: {{ env "ADMIN_CLIENT_ID" }}
      adminClientSecret: {{ env "ADMIN_CLIENT_SECRET" }}
      clusterName: {{ env "CLUSTER_NAME" | quote }}
      installEmail: {{ env "INSTALL_EMAIL" | quote }}


    helmS3Bucket: {{ $s3Bucket }}
    helmS3Key: {{ $s3Key }}
    # helmS3Region:
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
