repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
{{ $serviceClientId  := requiredEnv "SERVICE_CLIENT_ID" }}
{{ $serviceClientSecret := requiredEnv "SERVICE_CLIENT_SECRET" }}
- name: openraven
  url: {{ $ourUrl }}

releases:
- name: cross-account
  namespace: ui
  chart: openraven/cross-account
  version: 0.153023673.0
  wait: false
  values:
  - global:
      groupId: {{ env "GROUP_ID" }}
      openravenIngressHostname: {{ $ingHostname }}
      serviceClientId: {{ $serviceClientId }}
      serviceClientSecret: {{ $serviceClientSecret }}

  - ingress:
      tls:
      - secretName: www-tls
        hosts:
        - {{ $ingHostname }}

  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
