repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
- name: openraven-repo
  url: {{ $ourUrl }}

releases:
- name: dmap-scheduler
  namespace: dmap
  chart: openraven-repo/dmap-scheduler
  version: 0.200665181.0
  wait: false

  values:
  - global:
      groupId: {{ requiredEnv "GROUP_ID" }}

  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
