{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
repositories:
  - name: openraven
    url: {{ $ourUrl }}

releases:
- name: etcd-prune
  namespace: kube-system
  chart: openraven/etcd-prune
  version: 0.1.0
