{{- $version := "7.0.5" }}
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: kafka
  namespace: kafka
  chart: bitnami/kafka
  # https://hub.helm.sh/charts/bitnami/kafka/7.0.5
  version: {{ $version }}
  values:
  - ./values/kafka/{{ $version }}.yaml
  # this apparently needs some TLC
  # needs:
  # - kube-system/default-storage-class
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
           kubectl create      namespace $my_ns
      fi
