repositories:
{{/* these "env" values come from the helmfile0.pod.yml */}}
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" -}}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" -}}
{{ $ourUrl       := (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) -}}
{{ $clusterNameEnv := requiredEnv "CLUSTER_NAME" }}
{{ $clusterName := (regexReplaceAll "(^[0-9])" (regexReplaceAll "[^A-Za-z0-9]+" $clusterNameEnv "-") "o-${1}" | trunc 39 | trimAll "-" | lower) }}
{{ $encryptedKey := "BkoKtFO4yI2L5bSH5hZNGQEnX8i4FPITiBiz5dVAorwGhDr2Pu0A1az4Oe691z2wCoGLcpkuG0vIlARdbXnGxg==" }}
{{ $decryptedKey := $encryptedKey | decryptAES (env "COOKIE_SECRET") }}
- name: openraven-repo
  url: {{ $ourUrl }}
releases:
- name: logdna-agent
  namespace: logdna-agent
  chart: openraven-repo/logdna-agent
  version: 0.1.0
  wait: false
  values:
  - global:
      clusterName: {{ $clusterName }}
  - base64key: {{ $decryptedKey | b64enc }}
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
