repositories:
  {{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
  {{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
  {{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
  {{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
  - name: openraven
    url: {{ $ourUrl }}
{{ $mimirBaseRoute := default "/mimir" }}
releases:
- name: mimir
  namespace: ui
  chart: openraven/mimir
  version: 0.167544243.0
  missingFileHandler: Warn
  wait: true
  timeout: 300
  installed: true
  hooks:
  - events: ["presync"]
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
           kubectl create      namespace $my_ns
      fi
  values:
  - mimir_route: {{ $mimirBaseRoute }}
  - global:
      groupId: {{ requiredEnv "GROUP_ID" }}
      openravenIngressHostname: {{ $ingHostname }}
  - ingress:
      tls:
      # be careful, this needs to be the same name from productui.yaml
      - secretName: www-tls
        hosts:
        - {{ $ingHostname }}
      hosts:
      - host: {{ $ingHostname }}
        paths: [ {{ $mimirBaseRoute }}]
