repositories:
  {{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
  {{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
  {{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
  {{ $clusterName  := requiredEnv "CLUSTER_NAME" | quote }}
  - name: openraven-repo
    url: {{ $ourUrl }}

releases:
- name: openraven-repo-admin
  namespace: kube-system
  chart: openraven-repo/openraven-admin
  version: 0.0.4
  values:
    - ./values/clusterType.yaml.gotmpl
    - group_name: {{ $clusterName }}
