repositories:
{{/* these "env" values come from the helmfile0.pod.yml */}}
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" -}}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" -}}
{{ $ourUrl       := (printf "https://%s.%s/monitoring" $s3Bucket $s3BucketHost) -}}
{{ $clusterNameEnv := requiredEnv "CLUSTER_NAME" }}
{{ $clusterName := (regexReplaceAll "(^[0-9])" (regexReplaceAll "[^A-Za-z0-9]+" $clusterNameEnv "-") "o-${1}" | trunc 39 | trimAll "-" | lower) }}
{{ $values := ((tpl (readFile "./values/clusterType.yaml.gotmpl") . ) | fromYaml) }}
{{ $clusterType := $values.global.clusterType }}
{{ $groupId := requiredEnv "GROUP_ID" }}
{{ $releaseChannel := $s3Bucket }}
- name: openraven-repo-monitoring
  url: {{ $ourUrl }}
releases:
- name: datadog
  namespace: datadog
  chart: openraven-repo-monitoring/openraven-datadog
  version: 0.0.3
  wait: false
  recreatePods: true
  installed: {{ not (eq $clusterType "dev") }}
  values:
  - ./values/clusterType.yaml.gotmpl
  - datadog:
      datadog: # The second datadog is a result of it being a sub-chart
        clusterName: {{ $clusterName }}
        tags:
          - "cluster_type:{{ $clusterType }}"
          - "group_id:{{ $groupId }}"
          - "release_channel:{{ $releaseChannel }}"
        logs:
          enabled: false
      clusterAgent:
        {{/* must be at least 32 chars */}}
        token: {{ sha256sum $groupId }}
        env:
          - name: DD_CLUSTER_CHECKS_EXTRA_TAGS
            value: "cluster_type:{{ $clusterType }} group_id:{{ $groupId }} release_channel:{{ $releaseChannel }}"
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
