repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
- name: openraven
  url: {{ $ourUrl }}

releases:
- name: ui
  namespace: ui
  chart: openraven/productui
  version: 0.5329.0
  missingFileHandler: Warn
  wait: true
  timeout: 300
  installed: true
  values:
  - global:
      frontEndClientId: {{ requiredEnv "FRONTEND_CLIENT_ID" }}
      groupId: {{ requiredEnv "GROUP_ID" }}
      serviceClientId: {{ requiredEnv "SERVICE_CLIENT_ID" }}
      serviceClientSecret: {{ requiredEnv "SERVICE_CLIENT_SECRET" }}
      openravenIngressHostname: {{ $ingHostname }}
  - ingress:
      tls:
      # this name doesn't *mean* anything, and will be created by cert-manager
      # thanks to the annotation above, although be careful because graph-explorer
      # needs(?) the same name
      - secretName: www-tls
        hosts:
        - {{ $ingHostname }}
  hooks:
  - events: ['presync']
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
           kubectl create      namespace $my_ns
      fi
