repositories:
{{ $s3Bucket     := env "HELM_S3_BUCKET"      | default "openraven-deploy" }}
{{ $s3BucketHost := env "HELM_S3_BUCKET_HOST" | default "s3.amazonaws.com" }}
{{ $ourUrl       := env "HELM_S3_URL"         | default (printf "https://%s.%s/charts" $s3Bucket $s3BucketHost) }}
{{ $groupId      := requiredEnv "GROUP_ID" }}
{{ $ingHostname  := requiredEnv "OPENRAVEN_INGRESS_HOSTNAME" }}
- name: openraven
  url: {{ $ourUrl }}

releases:
- name: s3-scan-service
  namespace: dmap
  chart: openraven/s3-scan-service
  version: 0.244064629.0
  installed: true
  hooks:
  - events: ["presync"]
    showlogs: true
    command: bash
    args:
    - -exc
    - |
      my_ns="{{`{{ .Release.Namespace }}`}}"
      if ! kubectl get -o name namespace $my_ns; then
        kubectl create namespace $my_ns
      fi
      kubectl annotate --overwrite ns $my_ns "iam.amazonaws.com/permitted=orvn-{{ $groupId }}-.*"
  values:
  - global:
      openravenIngressHostname: {{ $ingHostname }}
      groupId: {{ $groupId }}
