metrics:
  kafka:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.kafka.port }}"
        prometheus.io/path: "/metrics"
        ad.datadoghq.com/service.check_names: |
            ["openmetrics"]
        ad.datadoghq.com/service.init_configs: |
            [{}]
        ad.datadoghq.com/service.instances: |
            [
              {
                "prometheus_url": "http://%%host%%:{{ .Values.metrics.kafka.port }}/metrics",
                "namespace": "kafka",
                "metrics": ["*"]
              }
            ]
